# Generated by Django 4.2.4 on 2023-08-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField()),
                ('checkin_time', models.DateTimeField()),
                ('condition_on_checkout', models.TextField()),
                ('condition_on_checkin', models.TextField()),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='company_app.employee')),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='company_app.employee')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.device')),
            ],
        ),
    ]
