# Generated by Django 4.2.4 on 2023-08-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='company',
        ),
        migrations.AddField(
            model_name='device',
            name='current_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=10),
        ),
    ]
