# Generated by Django 4.2.4 on 2023-08-26 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_remove_device_company_device_current_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=10),
        ),
    ]
