# Generated by Django 4.2.4 on 2023-08-26 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_device_company_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
