# Generated by Django 4.2.4 on 2023-08-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_device_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='reference_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
