# Generated by Django 4.2.3 on 2023-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_alter_device_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
