# Generated by Django 4.2.3 on 2023-08-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_alter_devicelog_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='company_app.employee'),
        ),
    ]
